networks:
  hebewerk-starter:
    external: false
    name: ${HBWRK_PROJECT_NAME}

services:

  hebewerk-starter_server:
    extends:
      file: docker-compose-dev.yml
      service: hebewerk-starter_server

    # silent
    command: 'tail -f /dev/null'